FROM python:3.8
RUN apt-get update && apt-get install -y make libgl1-mesa-glx && rm -rf /var/lib/apt/lists/*
WORKDIR /roboflow-python
COPY .devcontainer/bashrc_ext /root/bashrc_ext
RUN echo "source /root/bashrc_ext" >> ~/.bashrc
COPY . .
RUN pip install -e ".[dev]"
