#!/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cp $SCRIPT_DIR/data/.config-prod $SCRIPT_DIR/data/.config
export API_URL=https://api.roboflow.com
export APP_URL=https://app.roboflow.com
export OBJECT_DETECTION_URL=https://detect.roboflow.one
export DEDICATED_DEPLOYMENT_URL=https://roboflow.cloud
export ROBOFLOW_CONFIG_DIR=$SCRIPT_DIR/data/.config
